# Generated by Django 5.0.7 on 2024-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('course', models.CharField()),
            ],
        ),
    ]
